---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
Outputs:
  S3Bucket:
    Description: S3 Bucket Name [Trial - 24]
    Value: !Ref S3Bucket